### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by scriptbypavan** [adiwajshing/Baileys#1197]
When I have connected with multi device and trying to send message, I am facing **UnhandledPromiseRejectionWarning: TypeError: nodeCrypto.diffieHellman is not a function** this error, can someone help me on this.

![image](https://user-images.githubusercontent.com/69261587/151008194-df1034e9-b886-49b9-9336-58d1871de91c.png)

**Comment by evaasmakula** [comment]
It's a connection problems

**Comment by scriptbypavan** [comment]
Even after trying to reconnect am unable to send a message. below is my code is nodejs.

`// import { Boom } from '@hapi/boom'
// import P from 'pino'
const makeWASocket = require("@adiwajshing/baileys");
const { makeWALegacySocket, AnyMessageContent, delay, DisconnectReason, makeInMemoryStore, useSingleFileAuthState } = require("@adiwajshing/baileys");

// the store maintains the data of the WA connection in memory
// can be written out to a file & read from it
// const store = makeInMemoryStore({ logger: P().child({ level: 'debug', stream: 'store' }) })
// store.readFromFile('./baileys_store_multi.json')
// // save every 10s
// setInterval(() => {
// 	store.writeToFile('./baileys_store_multi.json')
// }, 10_000)

const { state, saveState } = useSingleFileAuthState('./auth_info_multi.json')

// start a connection
const startSock = () => {
    
	const sock = makeWASocket.default({
		// logger: P({ level: 'trace' }),
		printQRInTerminal: true,
		auth: state,
		// implement to handle retries
		getMessage: async key => {
			return {
				conversation: 'hello'
			}
		}
	})

	// store.bind(sock.ev)

	const sendMessageWTyping = async (msg, jid) => {
		await sock.presenceSubscribe(jid)
		await delay(500)

		await sock.sendPresenceUpdate('composing', jid)
		await delay(2000)

		await sock.sendPresenceUpdate('paused', jid)

		await sock.sendMessage(jid, msg)
	}
    
	sock.ev.on('chats.set', item => console.log(`recv ${item.chats.length} chats (is latest: ${item.isLatest})`))
	sock.ev.on('messages.set', item => console.log(`recv ${item.messages.length} messages (is latest: ${item.isLatest})`))
	sock.ev.on('contacts.set', item => console.log(`recv ${item.contacts.length} contacts`))

	sock.ev.on('messages.upsert', async m => {
		console.log(JSON.stringify(m, undefined, 2))
        
		const msg = m.messages[0]
		if(!msg.key.fromMe && m.type === 'notify') {
			console.log('replying to', m.messages[0].key.remoteJid)
			// await sock!.sendReadReceipt(msg.key.remoteJid, msg.key.participant, [msg.key.id])
			await sendMessageWTyping({ text: 'Hello there!' }, msg.key.remoteJid)
		}
        
	})

	sock.ev.on('messages.update', m => console.log(m))
	sock.ev.on('message-receipt.update', m => console.log(m))
	sock.ev.on('presence.update', m => console.log(m))
	sock.ev.on('chats.update', m => console.log(m))
	sock.ev.on('contacts.upsert', m => console.log(m))

	sock.ev.on('connection.update', (update) => {
		const { connection, lastDisconnect } = update
		if(connection === 'close') {
			// reconnect if not logged out
			startSock()
			// if((lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut) {
			// } else {
			// 	console.log('connection closed')
			// }
		}
        
		console.log('connection update', update)
	})
	// listen for when the auth credentials is updated
	sock.ev.on('creds.update', saveState)

	return sock
}

startSock()`

**Comment by scriptbypavan** [comment]
This is resolved once I upgraded to latest node version.

**Comment by Paiyah** [comment]
![Screenshot_20220727_224132](https://user-images.githubusercontent.com/109099078/181442481-f9eaa0f8-5c23-4980-9862-ce5e8e43185c.jpg)
Help me please

**Comment by evaasmakula** [comment]
> hen I have connected with multi device and trying to send message, I

its seem you forgot to import `useSingleFileAuthState` just try to import it `import makeWASocket, {useSingleFileAuthState} from '@adiwajshing/baileys'`

**Comment by DreamLikeAmonster** [comment]
SyntaxError: Identifier 'makeWASocket' has already been declared
