### ISSUE TITLE
[BUG] member limit

### ISSUE THREAD

**Issue by takimtod** [adiwajshing/Baileys#1803]
Wanted to know how to resolve the issue of not working in groups with more than 257 members, in useMultiFileAuthState it gets messages on hold, already useSingleFileAuthState causes it to restart and does not perform any action.

**Comment by tiagomatrixd** [comment]
have you updated to the latest version?  It has been corrected.

**Comment by takimtod** [comment]
> sudah update ke versi terbaru? Ini telah diperbaiki.

**Comment by takimtod** [comment]
Yes, I'm using the latest version but it still doesn't respond to grub with more than 257 members
