### ISSUE TITLE
[BUG]  TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by felangga** [adiwajshing/Baileys#254]
I'm getting this error when sending an image/video
It's because the url isn't found when chat-update event called.

>  TypeError: Only absolute URLs are supported

The response when chat-update called
![image](https://user-images.githubusercontent.com/14814984/101125412-c31ec780-362b-11eb-83b5-0d546fdda9ed.png)

What it should be
![image](https://user-images.githubusercontent.com/14814984/101125448-db8ee200-362b-11eb-8644-a2c66e9f02a9.png)

**Comment by barkerpedro** [comment]
The error occurs whenever I send a media via the mobile device.

**Comment by ibnusyawall** [comment]
same problem, and i don't know what happened?

 @adiwajshing

**Comment by felangga** [comment]
Sometimes it's work, but sometimes it isn't

**Comment by adiwajshing** [comment]
When you send a media message from your phone, WA doesn't send the media info. You have to wait for it to arrive in another `chat-update`. You can do this by:

```

let m = MESSAGE_YOU_WANT_TO_DOWNLOAD

conn.on('chat-update', chat => {
  // if the message is updated
  if (conn.messages && conn.messages[0] && conn.messages[0].key.id === m.key.id) {
    m = conn.messages[0]
    // download media here
  }
})

```

Note:
1. The first chat-update lets you know about the message
2. The second chat-update provides you with the media url

**Comment by canove** [comment]
I faced the same problem, solved by checking if message has a "url", like this:

```
 if (
            !msg.message?.imageMessage?.url ||
            !msg.message?.audioMessage?.url ||
            !msg.message?.videoMessage?.url ||
            !msg.message?.stickerMessage?.url ||
            !msg.message?.documentMessage?.url
          )
            return;

          const mediaBuffer = await con.downloadMediaMessage(msg);
```

I think there's a more elegant way of doing this, I tried 
```
const messageType = Object.keys(msg.message)[0];        
          if (!msg.message?.[messageType]?.url) return;

          const mediaBuffer = await wbot.downloadMediaMessage(msg);
          await verifyMediaMessage(msg, mediaBuffer, ticket, contact);
```

But typescript yells on me:
![image](https://user-images.githubusercontent.com/24817866/101995770-5f3f7300-3cab-11eb-848d-e23dd9eecbc3.png)

**Comment by ariona** [comment]
hi @adiwajshing, This still not work, the second chat update does not include file URL.
here is first `chat-update`:
```js
WebMessageInfo {
  messageStubParameters: [],
  labels: [],
  key: MessageKey {
    remoteJid: '6281224630779@s.whatsapp.net',
    fromMe: true,
    id: '368EF4162D50D914EC6BED7792E86C0A'
  },
  message: Message {
    imageMessage: ImageMessage {
      interactiveAnnotations: [],
      scanLengths: [],
      mimetype: 'image/jpeg',
      jpegThumbnail: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff e2 02 28 49 43 43 5f 50 52 4f 46 49 4c 45 00 01 01 00 00 02 18 00 00 00 00 02 10 00 00 ... 2471 more bytes>
    }
  },
  messageTimestamp: Long { low: 1615702851, high: 0, unsigned: true },
  status: 4,
  epoch: 1001
}
```

and below is the second `chat-update`, it only added fileSha256, fileLenght, and fileEncSha256

```js
WebMessageInfo {
  messageStubParameters: [],
  labels: [],
  key: MessageKey {
    remoteJid: '6281224630779@s.whatsapp.net',
    fromMe: true,
    id: '368EF4162D50D914EC6BED7792E86C0A'
  },
  message: Message {
    imageMessage: ImageMessage {
      interactiveAnnotations: [],
      scanLengths: [],
      mimetype: 'image/jpeg',
      fileSha256: <Buffer ad 5e 9d 15 c2 64 15 c0 19 84 3f 9b 67 69 28 a6 e5 d7 4f 30 57 4c dc 4b 48 e6 59 0b 6e fe 1d ee>,
      fileLength: [Long],
      height: 490,
      width: 741,
      fileEncSha256: <Buffer a7 17 c6 e9 8e 38 ce 5f e1 f1 f1 89 59 0b 99 8d 12 3c 69 8a 03 16 fe 85 35 a7 54 74 7c ec 5f 50>,
      jpegThumbnail: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 84 00 1b 1b 1b 1b 1c 1b 1e 21 21 1e 2a 2d 28 2d 2a 3d 38 33 33 38 3d 5d 42 47 42 ... 520 more bytes>
    }
  },
  messageTimestamp: Long { low: 1615702851, high: 0, unsigned: true },
  status: 4,
  epoch: 1001
}
```

no file url there so the `downloadMediaMessage` method still return 
```
TypeError: Only absolute URLs are supported
```

Or can i generate url from these props? `fileSha256` / `fileEncSha256`, if yes can you point to the doc?
