### ISSUE TITLE
[BUG] MD - ACK stream error closing connection after 50 minutes.

### ISSUE THREAD

**Issue by canove** [adiwajshing/Baileys#810]
**Describe the bug**
After connected, my session closes after 50 minutes.

**To Reproduce**
1. Created a new connection
2. Send and receive some messages
3. Wait for 50 minutes

**Expected behavior**
Connection keep working after 50 minutes, without need to reconnect. 

**Environment (please complete the following information):**
 - Is this on a server?
 Yes
 - What do your `connectOptions` look like? 
 Like example.ts
 - Do you have multiple clients on the same IP?
 No
 - Are you using a proxy?
 Yes

**Additional context**
Logs:
```
2021-11-08T12:17:38-03:00 [1636384658113] INFO: connected to WA Web
2021-11-08T12:17:38-03:00 [1636384658214] INFO: handshake complete
2021-11-08T12:17:38-03:00 [1636384658214] INFO: logging in...
2021-11-08T12:17:38-03:00 [1636384658356] INFO: opened connection to WA
2021-11-08T12:17:38-03:00 [1636384658358] INFO: resyncing critical_block from v1
2021-11-08T12:17:38-03:00 [1636384658359] INFO: resyncing critical_unblock_low from v4
2021-11-08T12:17:38-03:00 [1636384658558] INFO: recv all pending notifications
2021-11-08T13:07:40-03:00 [1636387660723] INFO: connection closed
     error: {
       "data": {
         "tag": "stream:error",
         "attrs": {},
         "content": [
           {
             "tag": "ack",
             "attrs": {
               "id": "3EB0490AD762DE6451FB"
             },
             "content": null
           }
         ]
       },
       "isBoom": true,
       "isServer": false,
       "output": {
         "statusCode": 410,
         "payload": {
           "statusCode": 410,
           "error": "Gone",
           "message": "Stream Errored"
         },
        "headers": {}
      }
    }
2021-11-08T13:07:40-03:00 [1636387660727] INFO: connection closed
    error: {
      "data": null,
      "isBoom": true,
      "isServer": false,
      "output": {
        "statusCode": 428,
        "payload": {
          "statusCode": 428,
          "error": "Precondition Required",
          "message": "Connection Terminated by Server"
        },
        "headers": {}
      }
    }
2021-11-08T13:07:43-03:00 [1636387663738] INFO: RESTARTING
```

I've checked some message IDs displayed on ACK error, but I couldn't find anything. It occurs for messages with fromMe true and false.

**Comment by rawars** [comment]
Does anyone have a solution? this problem is presenting itself to me.

**Comment by canove** [comment]
I've added a "console.log" on `messages.update` event, and every time I restart my server, I get a lot of updates like this:

```
[
  {
    key: {
      remoteJid: 'xxxxx@s.whatsapp.net',
      id: '3EB08A82782C7422FD52',
      fromMe: false,
      participant: undefined
    },
    update: { status: 3 }
  }
]
[
  {
    key: {
      remoteJid: 'xxxxxx@s.whatsapp.net',
      id: '3EB08A82782C7422FD52',
      fromMe: false,
      participant: undefined
    },
    update: { status: 4 }
  }
]
```

The same IDS keep coming after each restart. If I stop sending and receiving messages for a long time, after a while, they stop coming. 

It seems that these repeated events are related to the 50 minute error, because when they show up after restart, I get the ACK stream error after 50 minutes connected, containing one of they ID's. 

When they not show up, I don't get stream erros and keep connected after 50 minutes.

To reproduce:

0 - add a console.log to 'messages.update' event.
1 - Start the server and connect. 
2 - Send or receive one message. (the event will be triggered and you should see your console.log)
3 - restart the server many times (the event will be triggered with the same messages on each restart)

Hope it helps.

**Comment by burstfreeze** [comment]
I can confirm ^

I would bet money on my previous statement, the server waits for some ack and keeps trying but will not proceed unless we ack the message. Or the soft-logout theory, also a good one. Or something completely different. Everything feels so close now

**Comment by canove** [comment]
I still don't know how to "clean" this pending message.updates, but after restarting the server around 20 times, they are gone.

**Comment by canove** [comment]
Fixed by: https://github.com/adiwajshing/Baileys/commit/cfa7e8ec66aab05baa30aeb1e167d149528f9f52

**Comment by canove** [comment]
It still occurs on some sessions. I still haven't got a consistent way to reproduce it.

**Comment by adiwajshing** [comment]
@canove 

1. ensure your connections were logged in on the latest commit
2. if issue persists, the incorrectly ack-ed notification will keep showing up on every reconnect. In this case, please put the logs for the notification that keeps showing up

**Comment by canove** [comment]
> @canove
> 
> 1. ensure your connections were logged in on the latest commit
> 2. if issue persists, the incorrectly ack-ed notification will keep showing up on every reconnect. In this case, please put the logs for the notification that keeps showing up

worked, thanks!

**Comment by rawars** [comment]
Good friends, I picked up a connection at two in the afternoon, but at five it got lost and I stopped listening, this is the exit through the terminal, I had it running on my local computer and on a server in aws at two it broke .

Also noteworthy that I have the last commit made.

![error50](https://user-images.githubusercontent.com/3655598/141709143-ddc6d127-3001-4c80-a465-3a64fb61e52b.png)

**Comment by canove** [comment]
@adiwajshing, It still happen sometimes. I test receiving a call on connected number, and now my connection restarts every 50 minutes again. 

Can you point me the way to solve this? I'll be glad to make a PR.

```
[1637798395634] INFO: connected to WA Web
[1637798395873] INFO: handshake complete
[1637798395873] INFO: logging in...
[1637798396112] INFO: opened connection to WA
[1637798396113] INFO: xxxxxxxxxxxx OPEN
[1637798396399] INFO: recv call
    node: {
      "tag": "call",
      "attrs": {
        "from": "xxxxxxxxxx@s.whatsapp.net",
        "id": "A1867E7A6A1E0132DE268264764E2250",
        "offline": "6",
        "t": "1637782764"
      },
      "content": [
        {
          "tag": "reject",
          "attrs": {
            "call-creator": "xxxxxxxx@s.whatsapp.net",
            "call-id": "4824752E55BBE31B6FC910D5F6DF8F73",
            "count": "0"
          },
          "content": null
        }
      ]
    }
[1637798396400] INFO: recv call
    node: {
      "tag": "call",
      "attrs": {
        "from": "xxxxxxx@s.whatsapp.net",
        "id": "F02882DFE596D09FFCB2AF562A8A851B",
        "offline": "1",
        "t": "1637782923"
      },
      "content": [
        {
          "tag": "reject",
          "attrs": {
            "call-creator": "xxxxxxx@s.whatsapp.net",
            "call-id": "910FA1491ABB50A1D90C1D267D8EE0E0",
            "count": "0"
          },
          "content": null
        }
      ]
    }
[1637798396401] INFO: got 2 offline messages/notifications
[1637801401219] ERROR: stream errored out
    error: {
      "tag": "stream:error",
      "attrs": {},
      "content": [
        {
          "tag": "ack",
          "attrs": {
            "id": "A1867E7A6A1E0132DE268264764E2250"
          },
          "content": null
        }
      ]
    }
[1637801401220] INFO: connection closed
    error: {
      "data": {
        "tag": "stream:error",
        "attrs": {},
        "content": [
          {
            "tag": "ack",
            "attrs": {
              "id": "A1867E7A6A1E0132DE268264764E2250"
            },
            "content": null
          }
        ]
      },
      "isBoom": true,
      "isServer": false,
      "output": {
        "statusCode": 410,
        "payload": {
          "statusCode": 410,
          "error": "Gone",
          "message": "Stream Errored"
        },
        "headers": {}
      }
    }
[1637801401221] INFO: xxxxxxxx CLOSE: Stream Errored
[1637801401222] INFO: connection closed
    error: {
      "data": null,
      "isBoom": true,
      "isServer": false,
      "output": {
        "statusCode": 428,
        "payload": {
          "statusCode": 428,
          "error": "Precondition Required",
          "message": "Connection Terminated by Server"
        },
        "headers": {}
      }
    }
[1637801404223] INFO: RESTARTING
```

**Comment by adiwajshing** [comment]
@canove this commit should fix: https://github.com/adiwajshing/Baileys/pull/696/commits/669fcaa43864522d38503f18e45563271101ccbf

**Comment by canove** [comment]
The call fix works greate, thanks!

I found one more case:
```
2021-11-25T06:08:36-03:00 [1637831316970] INFO: connected to WA Web
2021-11-25T06:08:37-03:00 [1637831317111] INFO: handshake complete
2021-11-25T06:08:37-03:00 [1637831317112] INFO: logging in...
2021-11-25T06:08:37-03:00 [1637831317333] INFO: opened connection to WA
2021-11-25T06:08:37-03:00 [1637831317335] INFO: XXXXX OPEN
2021-11-25T06:08:37-03:00 [1637831317943] INFO: got 4 offline messages/notifications
2021-11-25T06:08:37-03:00 [1637831317946] WARN: received node with 0 messages
2021-11-25T06:08:37-03:00     stanza: {
2021-11-25T06:08:37-03:00       "tag": "message",
2021-11-25T06:08:37-03:00       "attrs": {
2021-11-25T06:08:37-03:00         "from": "XXXXXX@s.whatsapp.net",
2021-11-25T06:08:37-03:00         "type": "text",
2021-11-25T06:08:37-03:00         "id": "3EB046A5FFAFFB0CD5E2",
2021-11-25T06:08:37-03:00         "offline": "11",
2021-11-25T06:08:37-03:00         "t": "1637801169",
2021-11-25T06:08:37-03:00         "notify": "XXXXX"
2021-11-25T06:08:37-03:00       },
2021-11-25T06:08:37-03:00       "content": [
2021-11-25T06:08:37-03:00         {
2021-11-25T06:08:37-03:00           "tag": "url_text",
2021-11-25T06:08:37-03:00           "attrs": {},
2021-11-25T06:08:37-03:00           "content": null
2021-11-25T06:08:37-03:00         },
2021-11-25T06:08:37-03:00         {
2021-11-25T06:08:37-03:00           "tag": "url_number",
2021-11-25T06:08:37-03:00           "attrs": {},
2021-11-25T06:08:37-03:00           "content": null
2021-11-25T06:08:37-03:00         },
2021-11-25T06:08:37-03:00         {
2021-11-25T06:08:37-03:00           "tag": "unavailable",
2021-11-25T06:08:37-03:00           "attrs": {},
2021-11-25T06:08:37-03:00           "content": null
2021-11-25T06:08:37-03:00         }
2021-11-25T06:08:37-03:00       ]
2021-11-25T06:08:37-03:00     }
2021-11-25T06:58:44-03:00 [1637834324572] ERROR: stream errored out
2021-11-25T06:58:44-03:00     error: {
2021-11-25T06:58:44-03:00       "tag": "stream:error",
2021-11-25T06:58:44-03:00       "attrs": {},
2021-11-25T06:58:44-03:00       "content": [
2021-11-25T06:58:44-03:00         {
2021-11-25T06:58:44-03:00           "tag": "ack",
2021-11-25T06:58:44-03:00           "attrs": {
2021-11-25T06:58:44-03:00             "id": "3EB046A5FFAFFB0CD5E2"
2021-11-25T06:58:44-03:00           },
2021-11-25T06:58:44-03:00           "content": null
2021-11-25T06:58:44-03:00         }
2021-11-25T06:58:44-03:00       ]
2021-11-25T06:58:44-03:00     }
2021-11-25T06:58:44-03:00 [1637834324577] INFO: connection closed
2021-11-25T06:58:44-03:00     error: {
2021-11-25T06:58:44-03:00       "data": {
2021-11-25T06:58:44-03:00         "tag": "stream:error",
2021-11-25T06:58:44-03:00         "attrs": {},
2021-11-25T06:58:44-03:00         "content": [
2021-11-25T06:58:44-03:00           {
2021-11-25T06:58:44-03:00             "tag": "ack",
2021-11-25T06:58:44-03:00             "attrs": {
2021-11-25T06:58:44-03:00               "id": "3EB046A5FFAFFB0CD5E2"
2021-11-25T06:58:44-03:00             },
2021-11-25T06:58:44-03:00             "content": null
2021-11-25T06:58:44-03:00           }
2021-11-25T06:58:44-03:00         ]
2021-11-25T06:58:44-03:00       },
2021-11-25T06:58:44-03:00       "isBoom": true,
2021-11-25T06:58:44-03:00       "isServer": false,
2021-11-25T06:58:44-03:00       "output": {
2021-11-25T06:58:44-03:00         "statusCode": 410,
2021-11-25T06:58:44-03:00         "payload": {
2021-11-25T06:58:44-03:00           "statusCode": 410,
2021-11-25T06:58:44-03:00           "error": "Gone",
2021-11-25T06:58:44-03:00           "message": "Stream Errored"
2021-11-25T06:58:44-03:00         },
2021-11-25T06:58:44-03:00         "headers": {}
2021-11-25T06:58:44-03:00       }
2021-11-25T06:58:44-03:00     }
2021-11-25T06:58:44-03:00 [1637834324579] INFO: XXXXX CLOSE: Stream Errored
```

**Comment by adiwajshing** [comment]
That's so weird. Try this one: https://github.com/adiwajshing/Baileys/pull/696/commits/1f8663092fa8ee7e3791e6f1636ac94e435249b1

**Comment by canove** [comment]
Trying, I'll not if it works in 50 minutes

**Comment by adiwajshing** [comment]
You don't need to wait for 50mins -- if you just restart the connection -- the same pending notification would not appear

**Comment by canove** [comment]
> You don't need to wait for 50mins -- if you just restart the connection -- the same pending notification would not appear
Works!
